import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  AcademicCapIcon,
  ChartBarIcon,
  CpuChipIcon,
  DocumentArrowUpIcon,
  SparklesIcon,
  UserGroupIcon
} from '@heroicons/react/24/outline';

const HomePage = () => {
  const features = [
    {
      icon: DocumentArrowUpIcon,
      title: 'AI Resume Analysis',
      description: 'Upload your resume and let our AI extract your skills automatically using advanced NLP techniques.'
    },
    {
      icon: ChartBarIcon,
      title: 'Skill Assessment',
      description: 'Take adaptive assessments that adjust difficulty based on your performance to accurately measure your skills.'
    },
    {
      icon: SparklesIcon,
      title: 'Personalized Learning',
      description: 'Get customized learning paths generated by machine learning algorithms tailored to your goals.'
    },
    {
      icon: CpuChipIcon,
      title: 'ML-Powered Recommendations',
      description: 'Receive intelligent course and resource recommendations based on your skill gaps and learning preferences.'
    },
    {
      icon: AcademicCapIcon,
      title: 'Progress Tracking',
      description: 'Monitor your learning journey with detailed analytics and visualizations of your skill development.'
    },
    {
      icon: UserGroupIcon,
      title: 'Community Learning',
      description: 'Connect with learners who have similar goals and share your learning experiences.'
    }
  ];

  return (
    <div className="home-page">
      {/* Hero Section */}
      <section className="home-hero">
        <div className="container">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1>
              <CpuChipIcon className="w-16 h-16 inline-block mr-4" />
              AI-Powered Learning System
            </h1>
            <p>
              Transform your career with personalized learning paths powered by artificial intelligence. 
              Discover your skills, assess your knowledge, and get tailored recommendations for growth.
            </p>
            <div className="hero-actions">
              <Link to="/register" className="hero-btn primary">
                <SparklesIcon className="w-5 h-5" />
                Get Started Free
              </Link>
              <Link to="/login" className="hero-btn secondary">
                Sign In
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features-section">
        <div className="container">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.8 }}
            className="section-header"
          >
            <h2>Powered by Advanced AI Technology</h2>
            <p>Our platform uses cutting-edge machine learning to provide personalized learning experiences</p>
          </motion.div>

          <div className="features-grid">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="feature-card"
              >
                <div className="feature-icon">
                  <feature.icon className="w-8 h-8" />
                </div>
                <h3>{feature.title}</h3>
                <p>{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="how-it-works">
        <div className="container">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.8 }}
            className="section-header"
          >
            <h2>How It Works</h2>
            <p>Get started in just three simple steps</p>
          </motion.div>

          <div className="steps-grid">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
              className="step-card"
            >
              <div className="step-number">1</div>
              <h3>Upload & Analyze</h3>
              <p>Upload your resume or enter your skills manually. Our AI will analyze and extract your current skill set.</p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="step-card"
            >
              <div className="step-number">2</div>
              <h3>Assess & Evaluate</h3>
              <p>Take adaptive assessments to accurately measure your proficiency levels across different skills.</p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.4 }}
              className="step-card"
            >
              <div className="step-number">3</div>
              <h3>Learn & Grow</h3>
              <p>Follow your personalized learning path with curated resources and track your progress in real-time.</p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <div className="container">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.8 }}
            className="cta-content"
          >
            <h2>Ready to Transform Your Learning Journey?</h2>
            <p>Join thousands of learners who are already using AI to accelerate their career growth.</p>
            <Link to="/register" className="cta-button">
              Start Your Journey Today
              <SparklesIcon className="w-5 h-5 ml-2" />
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default HomePage;
